package io.codemine.java.postgresql.codecs;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.ByteBuffer;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * Tests that range text literals with non-canonical bound forms survive encode/decode round trips
 * in both text and binary wire formats.
 *
 * <p>The existing property tests in {@link io.codemine.java.postgresql.CodecTestBase} only exercise
 * values generated by {@link Codec#random}. Before the fix, {@code random()} always produced the
 * canonical {@code [lower, upper)} form (inclusive lower, exclusive upper), so the tests were
 * self-consistent but never exercised:
 *
 * <ul>
 *   <li>exclusive lower bound with a finite value — e.g. {@code (1.0,5.0)}
 *   <li>inclusive upper bound — e.g. {@code [1.0,5.0]}
 *   <li>mixed non-canonical bounds — e.g. {@code (1.0,5.0]}
 * </ul>
 *
 * <p>These tests encode a known literal as text, then decode it, then re-encode it and assert the
 * result equals the original literal. The same sequence is repeated through the binary wire format.
 */
class RangeBoundsTest {

  /**
   * A text literal survives {@code decodeInText} → {@code encodeInText}.
   *
   * <p>Exercises all four bound-inclusivity combinations for a continuous range type ({@code
   * numrange}) so that all combinations are semantically distinct (PostgreSQL does not canonicalise
   * continuous types).
   */
  @ParameterizedTest
  @ValueSource(strings = {"[1.0,5.0)", "(1.0,5.0)", "[1.0,5.0]", "(1.0,5.0]", "empty", "(,)"})
  void textRoundTrip(String literal) throws Exception {
    var decoded = Codec.NUMRANGE.decodeInText(literal, 0).value;
    var sb = new StringBuilder();
    Codec.NUMRANGE.encodeInText(sb, decoded);
    assertEquals(literal, sb.toString());
  }

  /**
   * A text literal survives {@code decodeInText} → {@code encodeInBinary} → {@code decodeInBinary}
   * → {@code encodeInText}.
   *
   * <p>Verifies that the binary flags {@code RANGE_LB_INC} and {@code RANGE_UB_INC} are set and
   * read back correctly for all bound combinations.
   */
  @ParameterizedTest
  @ValueSource(strings = {"[1.0,5.0)", "(1.0,5.0)", "[1.0,5.0]", "(1.0,5.0]", "empty", "(,)"})
  void binaryRoundTrip(String literal) throws Exception {
    var fromText = Codec.NUMRANGE.decodeInText(literal, 0).value;
    byte[] binary = Codec.NUMRANGE.encodeInBinaryToBytes(fromText);
    var fromBinary = Codec.NUMRANGE.decodeInBinary(ByteBuffer.wrap(binary), binary.length);
    var sb = new StringBuilder();
    Codec.NUMRANGE.encodeInText(sb, fromBinary);
    assertEquals(literal, sb.toString());
  }
}
